BW\UserBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: BW\UserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 25
            unique: true
        password:
            type: string
            length: 64
        salt:
            type: string
            length: 32
        email:
            type: string
            length: 60
            unique: true
        enabled:
            column: enabled
            type: boolean
    oneToOne:
        profile:
            targetEntity: BW\UserBundle\Entity\Profile
            mappedBy: user
    manyToMany:
        roles:
            targetEntity: BW\UserBundle\Entity\Role
            inversedBy: users
    lifecycleCallbacks: {  }
