bu_project:
    resource: "@BUProjectBundle/Controller/"
    type:     annotation
    prefix:   /

bu_blog:
    resource: "@BUBlogBundle/Controller/"
    type:     annotation
    prefix:   /

bu_app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
